version: '3.5'

services:
  db-perfil:
    image: postgres:latest
    env_file:
      - .env
    networks:
      - proxynet

  web-perfil:
    build: .
    command: /code/runserver.sh
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    depends_on:
      - db-perfil
    env_file:
      - .env
    networks:
      - proxynet

networks:
  proxynet:
    name: EstudePlus-network