apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: profile-manager
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: profile-deploy 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: profile-manager
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: profile-config
            optional: false
        image: estudeplus/profile-manager
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
        name: profile-container
        ports:
          - containerPort: 8000
